
logging.config: classpath:log-dev.xml

spring.application.name: fastbood-user


spring.dubbo:
  scan: com.jonas.fastfood
  protocol:
    name: dubbo
    port: 20881
  application:
    name: ${spring.application.name}
    registry:
      address: zookeeper://127.0.0.1:2181
      timeout: 10000

