
logging.config: classpath:log-dev.xml

server.port: 8808

spring.application.name: fastfood-controller


spring.dubbo:
  scan: com.jonas.fastfood
  application:
    name: ${spring.application.name}
    registry:
      #address: zookeeper://127.0.0.1:2181
      address: zookeeper://43.229.153.43:2181
      timeout: 10000
