
logging.config: classpath:log-dev.xml

server.port: 8808

spring:
  application.name: fastfood-controller
  mvc.throw-exception-if-no-handler-found: true
  resources.add-mappings: false
  session:
    store-type: redis
  redis:
    host: 127.0.0.1
    port: 6379
    password:
  http.multipart:
     maxFileSize: 12Mb
     maxRequestSize: 20Mb

spring.dubbo:
  scan: com.jonas.fastfood
  application:
    name: ${spring.application.name}
    registry:
      address: zookeeper://43.229.153.43:2181
      timeout: 10000
