
logging.config: classpath:log-dev.xml

server.port: 8809

spring.application.name: fastbood-web


spring.dubbo:
  scan: com.jonas.fastfood
  application:
    name: ${spring.application.name}
    registry:
      address: zookeeper://127.0.0.1:2181
      timeout: 10000

